INSERT INTO CART (CART_ID,CREATION_DATE,LAST_UPDATION_DATE) VALUES(2,TO_DATE('2019-07-03 00:01:00','YYYY-MM-DD HH:MM:SS'),TO_DATE('2019-07-03 00:01:00','YYYY-MM-DD HH:MM:SS'))

INSERT INTO CUSTOMER (CUSTOMER_ID,DATE_OF_BIRTH,EMAIL_ADDRESS,FIRST_NAME,GENDER,LAST_NAME ,LOGIN_STATUS,MARITAL_STATUS,MIDDLE_NAME,PASS_WORD ,USER_NAME,CART_ID) VALUES(3,TO_DATE('1990-01-22 00:01:00','YYYY-MM-DD HH:MM:SS'),'nikhil.chavan@gmail.com','Nikhil','M','Chavan',FALSE,'S','Chandrakant','12345678','Nikhil',2)

INSERT INTO PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE) VALUES(1,'Parle-G Biscuit',10.50)
INSERT INTO PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE) VALUES(2,'Pepsi Bottle 1.5L',42.25)
INSERT INTO PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE) VALUES(3,'Amul Butter 100g Packet',65.25)
INSERT INTO PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE) VALUES(4,'Maggi Noodles',25.75)
INSERT INTO PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE) VALUES(5,'Colgate Toothpaste',60.50)
INSERT INTO PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE) VALUES(6,'Toothbrush',35.25)